spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.189.141:3307/db_data?serverTimezone=Asia/Shanghai
    username: root
    password: qfjava
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL57Dialect
  data:
    elasticsearch:
      cluster-name: qfjava
      cluster-nodes: 39.105.189.141:9300